import Footer from '@/components/footer';
import Header from '@/components/header';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col md:max-w-screen-2xl md:mx-auto">
        <Header title="Corporate" />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
